# Generated by Django 4.2.7 on 2025-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusermodel',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Region'),
        ),
    ]
