# Generated by Django 4.2.7 on 2025-02-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_botusermodel_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusermodel',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('en', 'English'), ('ru', 'Русский')], default='uz', help_text='Choose language', max_length=5, verbose_name='Language'),
        ),
    ]
