# Generated by Django 4.2.7 on 2025-02-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_botusermodel_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='duas/')),
                ('caption', models.TextField()),
            ],
        ),
    ]
