# Generated by Django 4.2.7 on 2025-02-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dua'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamadanTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('suhoor_time', models.TimeField()),
                ('iftar_time', models.TimeField()),
                ('image', models.ImageField(upload_to='ramadan_posts/')),
                ('caption', models.TextField()),
            ],
            options={
                'unique_together': {('region', 'date')},
            },
        ),
    ]
