# Generated by Django 4.2.7 on 2025-02-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ramadantime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRamadanTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ramadan_images/', verbose_name='Timetable Image')),
                ('caption', models.TextField(verbose_name='Caption with Time Differences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
